# Use the official Nginx image from Docker Hub
FROM --platform=linux/arm64 arm64v8/nginx:latest

# Remove the default nginx website
RUN rm -rf /usr/share/nginx/html/*

# Copy your static HTML files into the container
COPY ./html /usr/share/nginx/html

# Expose port 80
EXPOSE 80

# Start Nginx when the container launches
CMD ["nginx", "-g", "daemon off;"]
