# Use the official Nginx image from Docker Hub
FROM nginxinc/nginx-unprivileged:stable

# Copy your static HTML files into the container
COPY ./html /usr/share/nginx/html

# Start Nginx when the container launches
CMD ["nginx", "-g", "daemon off;"]