env: dev
namespace: streetcrocketdev
appName: streetcrocketdk

replicaCount: 2

image:
  repository: rg.fr-par.scw.cloud/crn-shared-prd-scr-lz-fr-par/tgc-streetcrocketcom-app
  tag: latest
  pullSecret: scr-pull

service:
  port: 80

serviceAccount:
  name: streetcrocketcom-sa

httproute:
  gatewayName: gateway
  gatewayNamespace: gatewayapi

nodeSelector:
  "node-role.kubernetes.io/worker": ""
  