kind: Service
apiVersion: v1
metadata:
  name: aks-streetcroquet
  namespace: streetcroquet
spec:
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  selector:
    app: aks-streetcroquet