name: Build and publish images

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

permissions:
  id-token: write
  contents: read
  pull-requests: write

jobs:
  deploy_infrastructure:
    name: Deploy PRD infrstructure code
    runs-on: ubuntu-latest
    environment: prd
    outputs:
      static_web_app_resource_name_output: ${{ steps.terraform_outputs.outputs.static_web_app_resource_name_output }}

    defaults:
      run:
        working-directory: ./src/webapp
    
    env:
      image_name: streetcroquetdk
      acr_registry: tgclzdevacr.azurecr.io

    steps:
    - uses: actions/checkout@v3

    - run: |
        docker --version
    
    - name: 'Az CLI login'
      uses: azure/login@v2
      with:
          client-id: ${{ secrets.HOMEAUTOMATION_DEV_CLIENT_ID }}
          tenant-id: ${{ secrets.HOMEAUTOMATION_DEV_TENANT_ID }}
          subscription-id: ${{ secrets.HOMEAUTOMATION_DEV_SUBSCRIPTION_ID }}
    
    - run: |
        az acr login --name tgclzdevacr.azurecr.io
        cd src/TGC.HomeAutomation

        docker build . -t $acr_registry/$image_name:${{ github.sha }}
        docker build . -t $acr_registry/$image_name:latest

        docker push $acr_registry/$image_name:${{ github.sha }}
        docker push $acr_registry/$image_name:latest
      name: "Build and publish webapp to ACR"