 # # # # # # # # # # # # # # # # # # # # # # # #
# REPLACE THE FOLLOWING VARIABLES AND ADJUST 
# - ENVIRONMENT_REFERENCE
# - CLIENT_ID_SECRET_REFERENCE
# - SUBSCRIPTION_ID_SECRET_REFERENCE
# - TENANT_ID_SECRET_REFERENCE
# - RESOURCE_GROUP_REFERENCE
# - STORAGE_ACCOUNT_REFERENCE
# - CONTAINER_NAME_REFERENCE
#
# # # # # # # # # # # # # # # # # # # # # # # # #

name: Deploy StreetCroquet.com

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:
    inputs:
      tfApply:
        description: 'Terraform apply?'
        required: true
        type: boolean
        default: false

permissions:
  id-token: write
  contents: read
  pull-requests: write

jobs:
  deploy_infrastructure:
    runs-on: ubuntu-latest
    environment: prd #Should be changed, lol
    defaults:
      run:
        working-directory: ./terraform
    
    env:
      ARM_CLIENT_ID: "${{ secrets.STREETCROQUETDK_PRD_CLIENT_ID }}"
      ARM_SUBSCRIPTION_ID: "${{ secrets.STREETCROQUETDK_PRD_SUBSCRIPTION_ID }}"
      ARM_TENANT_ID: "${{ secrets.STREETCROQUETDK_PRD_TENANT_ID }}"
      ARM_USE_AZUREAD: true

    steps:
    - uses: actions/checkout@v3

    - name: Install Terraform
      run: bash "${{ github.workspace }}/.github/scripts/install_terraform.sh" 

    - name: Terraform Fmt
      run: terraform fmt -check

    - name: Terraform Init
      run: |
        terraform init \
        -backend-config=resource_group_name="${{ secrets.STREETCROQUETDK_PRD_TFSTATE_RESOURCE_GROUP_NAME }}" \
        -backend-config=storage_account_name="${{ secrets.STREETCROQUETDK_PRD_TFSTATE_STORAGE_ACCOUNT_NAME }}" \
        -backend-config=container_name="${{ secrets.STREETCROQUETDK_PRD_TFSTATE_STORAGE_CONTAINER_NAME }}" \
        -backend-config=key="streetcroquet.tfstate"
        
    - name: Terraform Validate
      run: terraform validate

    - name: Terraform Plan
      id: plan
      run: terraform plan -input=false -var-file="envs/vars.prd.tfvars" -out=tfplan

    - name: Terraform Apply
      if: github.event.inputs.tfApply == 'true' && github.event_name != 'push' && github.event_name != 'pull_request'
      run: terraform apply -auto-approve tfplan
    
    - name: Set output
      id: terraform_outputs
      if: github.event.inputs.tfApply == 'true' && github.event_name != 'push' && github.event_name != 'pull_request'
      run: echo "static_web_app_resource_name_output="$(terraform output static_web_app_resource_name)"" >> $GITHUB_OUTPUT
  
  deployment_job_prd:
    runs-on: ubuntu-latest
    environment: prd
    needs: deploy_infrastructure
    name: Deploy PRD application code
    
    steps:
    - uses: actions/checkout@v3

    - name: Azure login
      uses: azure/login@v2
      with:
        client-id: ${{ secrets.STREETCROQUETDK_PRD_CLIENT_ID }}
        tenant-id: ${{ secrets.STREETCROQUETDK_PRD_TENANT_ID }}
        subscription-id: ${{ secrets.STREETCROQUETDK_PRD_SUBSCRIPTION_ID }}

    - name: Fetch SWA Token
      id: fetchSWAToken
      uses: azure/CLI@v1
      with: 
          inlineScript: |
              localdeploymentToken=$(az staticwebapp secrets list --name "${{ needs.deploy_infrastructure.outputs.static_web_app_resource_name_output }}" --query "properties.apiKey" -o tsv)
              echo "::add-mask::$localdeploymentToken"
              echo "deploymenttoken=$localdeploymentToken" >> "$GITHUB_OUTPUT"
              echo "Fetched token."
      
    - name: Build And Deploy
      id: builddeploy
      uses: Azure/static-web-apps-deploy@v1
      with:
        azure_static_web_apps_api_token: ${{steps.fetchSWAToken.outputs.deploymenttoken}}
        action: "upload"
        app_location: ./src/webapp
        api_location: ""
        skip_app_build: true
        skip_api_build: true
        config_file_location: ./src/webapp